version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      MONGO_URI: mongodb://mongo:27017/resume-builder
      JWT_SECRET: your_jwt_secret
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:5.0
    container_name: mongo_db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
